export { trimIndent } from './text/trimIndent.js';
export { textWrap } from './text/textWrap.js';
export type { TextWrapOptions } from './text/textWrap.js';
export { textDetectLineEnding } from './text/textDetectLineEnding.js';
export { textNormalizeLineEnding } from './text/textNormalizeLineEnding.js';
export { textGetDefaultLineEnding } from './text/textGetDefaultLineEnding.js';
export { textDetectEncoding } from './text/textDetectEncoding.js';
export { findActiveWord, findActiveWordString, getActiveWordQuery } from './text/findActiveWord.js';
export type { ActiveWord } from './text/findActiveWord.js';
export { suggestionApply } from './text/suggestionApply.js';
export { deterministicStringify, deepEqual, objectKey, hashObject } from './objects/deterministicJson.js';
export type { DeterministicJsonOptions } from './objects/deterministicJson.js';
export { AsyncLock } from './async/lock.js';
export { InvalidateSync, ValueSync } from './async/sync.js';
export { backoff, delay } from './async/time.js';
export { log } from './log.js';